# Generated by Django 2.0 on 2020-03-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=50),
        ),
    ]
