# Generated by Django 2.0 on 2020-03-05 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('calories', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('hungry', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0.0)),
                ('birthday', models.DateTimeField(default=None)),
                ('age', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.Food')),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pettype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.PetType'),
        ),
    ]
