# Generated by Django 2.0 on 2020-03-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0002_owner_specialty_vet_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='pet',
            new_name='pet_id',
        ),
    ]
