# Generated by Django 2.0 on 2020-03-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0003_auto_20200310_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='pet_id',
            new_name='pet',
        ),
    ]
