# Generated by Django 2.0.5 on 2020-03-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0002_auto_20200316_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='weight',
        ),
    ]
